import { useState } from "react";
import { ChevronRight, DollarSign, Loader2, Plus, Trash2 } from "lucide-react";
import { format } from "date-fns";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useLanguage } from "@/contexts/LanguageContext";
import { useShopFormatting } from "@/hooks/useShopFormatting";
import { useCreateOtherIncome, useDeleteOtherIncome } from "@/hooks/useOtherIncome";
import type { OtherIncome } from "@/hooks/useOtherIncome";

const categories = ["Consulting", "Rent", "Grant", "Interest", "Other"];

export function OtherIncomePanel({ income }: { income: OtherIncome[] }) {
  const { language } = useLanguage();
  const { formatMoney } = useShopFormatting();
  const createIncome = useCreateOtherIncome();
  const deleteIncome = useDeleteOtherIncome();
  const [showForm, setShowForm] = useState(false);
  const [selected, setSelected] = useState<OtherIncome | null>(null);
  const [form, setForm] = useState({ title: "", category: "Other", amount: "", date: format(new Date(), "yyyy-MM-dd"), payment_method: "Cash", notes: "" });
  const total = income.reduce((sum, item) => sum + Number(item.amount || 0), 0);

  const save = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!form.title.trim() || Number(form.amount) <= 0) return;
    await createIncome.mutateAsync({ ...form, title: form.title.trim(), amount: Number(form.amount), notes: form.notes.trim() || null });
    setForm({ title: "", category: "Other", amount: "", date: format(new Date(), "yyyy-MM-dd"), payment_method: "Cash", notes: "" });
    setShowForm(false);
  };

  return (
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
      <Card className="border-border bg-card shadow-xs">
        <CardHeader className="flex-row items-center justify-between border-b border-border p-4">
          <div><CardTitle className="text-sm font-bold">{language === "sw" ? "Mapato mengine" : "Other income"}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{language === "sw" ? "Mapato yasiyotokana na mauzo ya bidhaa au huduma." : "Income not generated by a product or service sale."}</p></div>
          <Button onClick={() => { setShowForm(true); setSelected(null); }} className="h-9 gap-1.5 rounded-xl text-xs"><Plus className="h-3.5 w-3.5" />{language === "sw" ? "Ongeza mapato" : "Record income"}</Button>
        </CardHeader>
        <CardContent className="p-0">
          {income.length === 0 ? <div className="p-12 text-center text-sm text-muted-foreground">{language === "sw" ? "Hakuna mapato mengine bado." : "No other income recorded yet."}</div> : <div className="internal-table-scroll"><table className="w-full text-xs"><thead><tr className="border-b border-border bg-muted/40 text-left text-[11px] uppercase text-muted-foreground"><th className="px-4 py-3">{language === "sw" ? "Tarehe" : "Date"}</th><th className="px-4 py-3">{language === "sw" ? "Chanzo" : "Source"}</th><th className="px-4 py-3">{language === "sw" ? "Aina" : "Category"}</th><th className="px-4 py-3 text-right">{language === "sw" ? "Kiasi" : "Amount"}</th><th /></tr></thead><tbody>{income.map((item) => <tr key={item.id} onClick={() => { setSelected(item); setShowForm(false); }} className="cursor-pointer border-b border-border/60 hover:bg-muted/40"><td className="px-4 py-3 font-medium">{format(new Date(item.date), "MMM d, yyyy")}</td><td className="px-4 py-3 font-semibold">{item.title}</td><td className="px-4 py-3 text-muted-foreground">{item.category}</td><td className="px-4 py-3 text-right font-bold">{formatMoney(item.amount)}</td><td className="px-4 py-3 text-right"><ChevronRight className="ml-auto h-4 w-4 text-muted-foreground" /></td></tr>)}</tbody></table></div>}
        </CardContent>
      </Card>
      {showForm ? <Card className="h-fit border-border shadow-xs"><CardHeader><CardTitle className="text-sm">{language === "sw" ? "Rekodi mapato mengine" : "Record other income"}</CardTitle></CardHeader><CardContent><form onSubmit={save} className="space-y-3"><div><Label>{language === "sw" ? "Chanzo" : "Source"}</Label><Input value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder={language === "sw" ? "Mfano: Kodi ya chumba" : "e.g. Room rental"} required /></div><div><Label>{language === "sw" ? "Kategoria" : "Category"}</Label><Select value={form.category} onValueChange={(value) => setForm({ ...form, category: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{categories.map((category) => <SelectItem key={category} value={category}>{category}</SelectItem>)}</SelectContent></Select></div><div><Label>{language === "sw" ? "Kiasi" : "Amount"}</Label><Input type="number" min="1" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} required /></div><div className="grid grid-cols-2 gap-2"><div><Label>{language === "sw" ? "Tarehe" : "Date"}</Label><Input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} required /></div><div><Label>{language === "sw" ? "Malipo" : "Payment"}</Label><Select value={form.payment_method} onValueChange={(value) => setForm({ ...form, payment_method: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Cash">Cash</SelectItem><SelectItem value="M-Pesa">M-Pesa</SelectItem><SelectItem value="Bank">Bank</SelectItem></SelectContent></Select></div></div><Button type="submit" disabled={createIncome.isPending} className="w-full rounded-xl">{createIncome.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <DollarSign className="h-4 w-4" />}{language === "sw" ? "Hifadhi" : "Save income"}</Button></form></CardContent></Card> : selected ? <Card className="h-fit border-border shadow-xs"><CardHeader className="flex-row items-start justify-between"><div><CardTitle className="text-sm">{selected.title}</CardTitle><p className="text-xs text-muted-foreground">{selected.category}</p></div><Button variant="ghost" size="icon" onClick={() => deleteIncome.mutate(selected.id)} aria-label="Delete income"><Trash2 className="h-4 w-4 text-destructive" /></Button></CardHeader><CardContent><p className="text-2xl font-bold">{formatMoney(selected.amount)}</p><p className="mt-2 text-xs text-muted-foreground">{format(new Date(selected.date), "PPP")} · {selected.payment_method}</p></CardContent></Card> : <Card className="h-fit border-border bg-muted/20 shadow-xs"><CardContent className="p-5"><p className="text-xs text-muted-foreground">{language === "sw" ? "Jumla ya mapato mengine" : "Total other income"}</p><p className="mt-2 text-2xl font-bold">{formatMoney(total)}</p></CardContent></Card>}
    </div>
  );
}