import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "sw";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation (10 Olly Modules)
    "nav.overview": "Overview",
    "nav.purchases": "Purchases",
    "nav.production": "Production",
    "nav.sales": "Sales",
    "nav.inventory": "Inventory",
    "nav.customers": "Customers & Receivables",
    "nav.finance": "Finance & Expenses",
    "nav.hrm": "Employees / HR",
    "nav.reports": "Reports",
    "nav.settings": "Settings",

    // Legacy / Sub Navigation Keys
    "nav.dashboard": "Overview",
    "nav.categories": "Categories",
    "nav.orders": "Orders",
    "nav.todo": "To-Do",
    "nav.userManagement": "User Management",
    "nav.suppliers": "Suppliers",
    "nav.expenses": "Finance & Expenses",
    "nav.loyalty": "Loyalty",
    "nav.notifications": "Notifications",
    "nav.assets": "Assets",
    "nav.main": "Main",

    // Quick Actions
    "quick.newPurchase": "+ New Purchase",
    "quick.newSale": "+ New Sale",
    "quick.newExpense": "+ New Expense",
    "quick.newBatch": "+ New Run",

    // Header & Periods
    "header.home": "Home",
    "header.today": "Today",
    "header.thisWeek": "This Week",
    "header.thisMonth": "This Month",
    "header.thisYear": "This Year",
    "header.custom": "Custom Period",

    // Common Terms
    "common.all": "All",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.export": "Export",
    "common.import": "Import",
    "common.loading": "Loading...",
    "common.status": "Status",
    "common.actions": "Actions",
    "common.view": "View",
    "common.details": "Details",
    "common.close": "Close",
    "common.back": "Back",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirmDelete": "Confirm Delete",
    "common.confirmDeleteDescription": "Are you sure you want to delete this? This action cannot be undone.",

    // Purchases
    "purchases.title": "Purchases",
    "purchases.subtitle": "Manage supplier purchase orders, stock receipts, and supplier accounts.",
    "purchases.totalPurchases": "Total Purchases",
    "purchases.monthlySpending": "Monthly Spending",
    "purchases.pendingDeliveries": "Pending Deliveries",
    "purchases.activeSuppliers": "Active Suppliers",
    "purchases.newPurchase": "New Purchase",
    "purchases.tabOrders": "Purchase Orders / Stock In",
    "purchases.tabSuppliers": "Suppliers",
    "purchases.orderId": "Purchase ID",
    "purchases.supplier": "Supplier",
    "purchases.items": "Items & Quantities",
    "purchases.totalCost": "Total Cost",
    "purchases.status": "Status",
    "purchases.date": "Date & Time",
    "purchases.received": "Received",
    "purchases.pending": "Pending",
    "purchases.cancelled": "Cancelled",

    // Production Aliases
    "production.inProgress": "In Progress",
    "production.completed": "Completed",
    "production.planned": "Planned",
    "production.cancelled": "Cancelled",
    "purchases.selectSupplier": "Select Supplier",
    "purchases.noSupplier": "No Supplier (Direct / Walk-in)",
    "purchases.selectProduct": "Select Product",
    "purchases.quantity": "Quantity",
    "purchases.buyingPrice": "Unit Buying Price",
    "purchases.notes": "Notes / Invoice #",
    "purchases.addItem": "Add Another Product",
    "purchases.completePurchase": "Receive Stock & Save",
    "purchases.noPurchases": "No purchase orders recorded yet.",

    // Production
    "production.title": "Production",
    "production.subtitle": "Track manufacturing runs, input material consumption, and finished goods.",
    "production.activeRuns": "Active Runs",
    "production.completedToday": "Completed Today",
    "production.totalOutput": "Total Output Units",
    "production.materialCost": "Total Material Cost",
    "production.newRun": "New Production Run",
    "production.batchNumber": "Batch #",
    "production.outputProduct": "Output Product (Finished Good)",
    "production.rawMaterials": "Raw Materials (Inputs)",
    "production.quantityToProduce": "Target Batch Quantity",
    "production.quantityProduced": "Quantity Produced",
    "production.statusPlanned": "Planned",
    "production.statusInProgress": "In Progress",
    "production.statusCompleted": "Completed",
    "production.statusCancelled": "Cancelled",
    "production.startRun": "Start Production",
    "production.completeRun": "Complete Run & Update Stock",
    "production.cancelRun": "Cancel Run",
    "production.materialsPerUnit": "Quantity per finished unit",
    "production.totalRequired": "Total consumed",
    "production.noRuns": "No production batches recorded yet.",
    "production.notes": "Production Notes / Instructions",

    // HR & Finance Tabs
    "hrm.tabStaff": "Employees & Attendance",
    "hrm.tabUserAccess": "User Access & Roles",
    "expenses.tabExpenses": "Expenses",
    "expenses.tabBilling": "Billing & Subscriptions",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "At-a-glance view of your shop performance today.",
    "dashboard.todaySales": "Today Sales",
    "dashboard.transactions": "Transactions",
    "dashboard.lowStock": "Low Stock",
    "dashboard.cashVsMpesa": "Cash vs Digital Payments",
    "dashboard.receiptsIssued": "Receipts issued today",
    "dashboard.checkInventory": "Check inventory before closing",
    "dashboard.paymentSplit": "Today's payment split",
    "dashboard.salesTrend": "Sales Trend",
    "dashboard.stockByCategory": "Stock by Category",
    "dashboard.totalItems": "Total Items",
    "dashboard.alerts": "Alerts & Recent Activity",
    "dashboard.newSale": "New Sale",
    "dashboard.addProduct": "Add Product",
    "dashboard.recordExpense": "Record Expense",
    "dashboard.daily": "Daily",
    "dashboard.weekly": "Weekly",
    "dashboard.monthly": "Monthly",
    "dashboard.calculator": "Calculator",

    // Sales
    "sales.customer": "Customer",
    "sales.customerName": "Customer Name",
    "sales.phone": "Phone",
    "sales.walkIn": "Walk-in Customer",
    "sales.scanBarcode": "Scan (USB)",
    "sales.searchProducts": "Search Products",
    "sales.searchOrScan": "Search or scan with USB barcode scanner",
    "sales.cart": "Cart",
    "sales.barcodeOrSearch": "Barcode scan or search to add items",
    "sales.qty": "Qty",
    "sales.product": "Product",
    "sales.price": "Price",
    "sales.subtotal": "Subtotal",
    "sales.discount": "Discount",
    "sales.total": "Total",
    "sales.cash": "Cash",
    "sales.mpesa": "Mobile Money",
    "sales.mpesaCode": "Transaction Reference",
    "sales.transactionCode": "Transaction code",
    "sales.completeSale": "Complete Sale",
    "sales.printReceipt": "Print Receipt",
    "sales.saveAsDraft": "Save as Draft",
    "sales.invoice": "Invoice",
    "sales.autoGenerated": "Auto-generated invoice number",
    "sales.dateTime": "Date & Time",
    "sales.enterAmount": "Enter amount",
    "sales.enterPhone": "Enter customer phone number",
    "sales.selectCustomer": "Select customer",

    // Inventory
    "inventory.title": "Inventory",
    "inventory.searchPlaceholder": "Search inventory...",
    "inventory.import": "Import",
    "inventory.export": "Export",
    "inventory.addProduct": "Add Product",
    "inventory.category": "Category",
    "inventory.categories": "Categories",
    "inventory.code": "Code / SKU",
    "inventory.name": "Product Name",
    "inventory.stock": "Stock Quantity",
    "inventory.sellingPrice": "Selling Price",
    "inventory.buyingPrice": "Buying Price",
    "inventory.priceCol": "Price",
    "inventory.actions": "Actions",
    "inventory.low": "LOW",
    "inventory.profit": "Profit",
    "inventory.profitPercent": "Profit %",
    "inventory.totalStockValue": "Total Stock Value",
    "inventory.all": "All Inventory",
    "inventory.inStock": "In Stock",
    "inventory.lowStock": "Low Stock",
    "inventory.outOfStock": "Out of Stock",

    // Add Product
    "addProduct.title": "Add New Product",
    "addProduct.back": "Back to Inventory",
    "addProduct.generalInfo": "General Information",
    "addProduct.productName": "Product Name",
    "addProduct.productNamePlaceholder": "e.g. Paint Brush 4 inch",
    "addProduct.productCode": "Product Code (SKU)",
    "addProduct.category": "Category",
    "addProduct.selectCategory": "Select Category",
    "addProduct.addCategoryNow": "Add Category now",
    "addProduct.barcode": "Barcode",
    "addProduct.scanOrEnter": "Focus here and scan with USB scanner, or type",
    "addProduct.unitType": "Unit Type",
    "addProduct.pricingStock": "Pricing & Stock",
    "addProduct.buyingPrice": "Buying Price",
    "addProduct.sellingPrice": "Selling Price",
    "addProduct.initialStock": "Initial Stock Quantity",
    "addProduct.lowStockAlert": "Low Stock Alert Limit",
    "addProduct.lowStockHint": "Notifies when stock drops below this",
    "addProduct.cancel": "Cancel",
    "addProduct.save": "Save Product",
    "addProduct.productImage": "Product Image",

    // Categories
    "category.building": "Building Materials",
    "category.tools": "Tools",
    "category.electrical": "Electrical",
    "category.plumbing": "Plumbing",
    "category.paint": "Paints & Solvents",

    // Units
    "unit.piece": "Piece (pc)",
    "unit.kg": "Kilogram (kg)",
    "unit.meter": "Meter (m)",
    "unit.liter": "Liter (L)",
    "unit.box": "Box",

    // Customers
    "customers.title": "Customers",
    "customers.searchPlaceholder": "Search customer name or phone...",
    "customers.addCustomer": "Add Customer",
    "customers.name": "Customer Name",
    "customers.phoneNumber": "Phone Number",
    "customers.type": "Type",
    "customers.creditBalance": "Credit Balance (TSH)",
    "customers.contractor": "Contractor",
    "customers.retail": "Retail",
    "customers.pay": "Pay",
    "customers.history": "History",

    // Suppliers
    "suppliers.title": "Suppliers",
    "suppliers.totalSuppliers": "Total Suppliers",
    "suppliers.pendingPayments": "Pending Payments",
    "suppliers.lastPurchase": "Last Purchase",
    "suppliers.daysAgo": "Days Ago",
    "suppliers.searchPlaceholder": "Search supplier name or contact...",
    "suppliers.addSupplier": "Add Supplier",
    "suppliers.supplierName": "Supplier Name",
    "suppliers.contact": "Contact",
    "suppliers.pendingPayment": "Pending Payment (TSH)",
    "suppliers.paid": "Paid",

    // Expenses
    "expenses.title": "Expense Tracking",
    "expenses.totalExpenses": "TOTAL EXPENSES (OCT)",
    "expenses.operationalCosts": "OPERATIONAL COSTS",
    "expenses.stockPurchases": "STOCK PURCHASES",
    "expenses.utilitiesRent": "Utilities & Rent",
    "expenses.pendingInvoices": "pending invoices",
    "expenses.recentExpenses": "Recent Expenses",
    "expenses.searchPlaceholder": "Search expenses...",
    "expenses.date": "Date",
    "expenses.description": "Description",
    "expenses.category": "Category",
    "expenses.amount": "Amount",
    "expenses.payMethod": "Pay Method",
    "expenses.addNewExpense": "Add New Expense",
    "expenses.expenseTitle": "Expense Title",
    "expenses.expensePlaceholder": "e.g. Electric Bill",
    "expenses.amountTsh": "Amount",
    "expenses.paymentMethod": "Payment Method",
    "expenses.saveExpense": "Save Expense",
    "expenses.categoryBreakdown": "Category Breakdown",

    // Expense categories
    "expenseCategory.utilities": "Utilities",
    "expenseCategory.rent": "Rent",
    "expenseCategory.transport": "Transport",
    "expenseCategory.food": "Food",
    "expenseCategory.office": "Office",
    "expenseCategory.stock": "Stock Purchase",

    // Reports
    "reports.title": "Reports",
    "reports.salesSummary": "Sales Summary",
    "reports.stockReport": "Stock Report",
    "reports.profitLoss": "Profit & Loss",
    "reports.customerLedger": "Customer Ledger",
    "reports.exportPdf": "Export PDF",
    "reports.exportExcel": "Export Excel",
    "reports.salesPeriod": "Sales Summary (Selected Period)",
    "reports.bestSelling": "Best Selling Products",
    "reports.salesByCategory": "Sales by Category",
    "reports.recentTransactions": "Recent Transactions",
    "reports.customer": "Customer",
    "reports.payment": "Payment",
    "reports.status": "Status",
    "reports.completed": "Completed",
    "reports.salesTrend": "Sales Trend",
    "reports.topCustomers": "Top Customers",
    "reports.expenseBreakdown": "Expense Breakdown",
    "reports.lowStockProducts": "Low Stock Products",
    "reports.amount": "Amount",
    "reports.amountTsh": "Amount",
    "reports.noSalesData": "No sales data yet",
    "reports.noSalesYet": "No sales yet",
    "reports.noData": "No data",
    "reports.daily": "Daily",
    "reports.weekly": "Weekly",
    "reports.monthly": "Monthly",
    "reports.custom": "Custom",
    "reports.from": "From",
    "reports.to": "To",
    "reports.inventoryValuation": "Inventory Valuation",
    "reports.totalValue": "Total Value",
    "reports.totalProducts": "Total Products",
    "reports.lowStock": "Low Stock",
    "reports.outOfStock": "Out of Stock",
    "reports.valueByProduct": "Value by Product",
    "reports.product": "Product",
    "reports.cost": "Cost",
    "reports.value": "Value",
    "reports.profitAndLoss": "Profit & Loss",
    "reports.salesRevenue": "Sales Revenue",
    "reports.expenses": "Expenses",
    "reports.netProfit": "Net Profit",
    "reports.profitMargin": "Profit Margin",
    "reports.salesTab": "Sales",
    "reports.inventoryTab": "Inventory",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your shop settings, users, and preferences.",
    "settings.shopDetails": "Shop Details",
    "settings.shopName": "Shop Name",
    "settings.phoneNumber": "Phone Number",
    "settings.location": "Location",
    "settings.saveChanges": "Save Changes",
    "settings.languagePrefs": "Language & Preferences",
    "settings.language": "Language",
    "settings.english": "English",
    "settings.swahili": "Swahili",
    "settings.lowStockAlerts": "Low Stock Alerts",
    "settings.notifyLow": "Notify when items are low",
    "settings.autoPrint": "Auto Print Receipt",
    "settings.printAfterSale": "Print after each sale",
    "settings.backupRestore": "Backup & Restore",
    "settings.backupDesc": "Create a backup of your data or restore from a previous backup.",
    "settings.createBackup": "Create Backup",
    "settings.restoreBackup": "Restore Backup",
    "settings.lastBackup": "Last backup",
    "settings.userManagement": "User Management",
    "settings.addUser": "Add User",
    "settings.role": "Role",
    "settings.active": "Active",
    "settings.inactive": "Inactive",
    "settings.receiptCustomization": "Receipt Customization",
    "settings.receiptHeader": "Receipt Header",
    "settings.receiptFooter": "Receipt Footer",
    "settings.logo": "Logo",
    "settings.taxRate": "Tax Rate (%)",
    "settings.saveReceiptSettings": "Save Receipt Settings",

    // Receipt
    "receipt.title": "SALES RECEIPT",
    "receipt.invoice": "Invoice",
    "receipt.date": "Date",
    "receipt.customer": "Customer",
    "receipt.cashier": "Cashier",
    "receipt.qty": "Qty",
    "receipt.item": "Item",
    "receipt.price": "Price",
    "receipt.total": "Total",
    "receipt.subtotal": "Subtotal",
    "receipt.discount": "Discount",
    "receipt.grandTotal": "GRAND TOTAL",
    "receipt.paymentMethod": "Payment",
    "receipt.mpesaCode": "Transaction Reference",
    "receipt.thankYou": "Thank you for shopping with us!",
    "receipt.comeAgain": "Karibu tena!",

    // Inventory Category Bulk
    "inventory.changeCategory": "Change Category",
    "inventory.deleteSelected": "Delete Selected",
    "inventory.exportSelected": "Export Selected",
    "inventory.newCategory": "New category",
    "inventory.selectCategory": "Select category",
    "inventory.applyCategory": "Apply Category",
    "inventory.productsWillBeUpdated": "products will be updated.",
  },
  sw: {
    // Navigation (10 Olly Modules)
    "nav.overview": "Muhtasari",
    "nav.purchases": "Manunuzi",
    "nav.production": "Uzalishaji",
    "nav.sales": "Mauzo",
    "nav.inventory": "Hesabu ya Stoo",
    "nav.customers": "Wateja na Madeni",
    "nav.finance": "Fedha na Matumizi",
    "nav.hrm": "Wafanyakazi / HR",
    "nav.reports": "Ripoti",
    "nav.settings": "Mipangilio",

    // Legacy / Sub Navigation Keys
    "nav.dashboard": "Muhtasari",
    "nav.categories": "Kategoria",
    "nav.orders": "Maagizo",
    "nav.todo": "Orodha ya Kazi",
    "nav.userManagement": "Usimamizi wa Watumiaji",
    "nav.suppliers": "Wasambazaji",
    "nav.expenses": "Fedha na Matumizi",
    "nav.loyalty": "Uaminifu",
    "nav.notifications": "Arifa",
    "nav.assets": "Mali",
    "nav.main": "Kuu",

    // Quick Actions
    "quick.newPurchase": "+ Ununuzi Mpya",
    "quick.newSale": "+ Mauzo Mapya",
    "quick.newExpense": "+ Matumizi Mapya",
    "quick.newBatch": "+ Uzalishaji Mpya",

    // Header & Periods
    "header.home": "Nyumbani",
    "header.today": "Leo",
    "header.thisWeek": "Wiki Hii",
    "header.thisMonth": "Mwezi Huu",
    "header.thisYear": "Mwaka Huu",
    "header.custom": "Kipindi Maalum",

    // Common Terms
    "common.all": "Zote",
    "common.cancel": "Ghairi",
    "common.save": "Hifadhi",
    "common.delete": "Futa",
    "common.edit": "Hariri",
    "common.search": "Tafuta",
    "common.filter": "Chuja",
    "common.export": "Pakua",
    "common.import": "Ingiza",
    "common.loading": "Inapakia...",
    "common.status": "Hali",
    "common.actions": "Vitendo",
    "common.view": "Tazama",
    "common.details": "Maelezo",
    "common.close": "Funga",
    "common.back": "Rudi",
    "common.confirm": "Thibitisha",
    "common.yes": "Ndiyo",
    "common.no": "Hapana",
    "common.confirmDelete": "Thibitisha Kufuta",
    "common.confirmDeleteDescription": "Je, una uhakika unataka kufuta hii? Kitendo hiki hakiwezi kurudishwa.",

    // Purchases
    "purchases.title": "Manunuzi",
    "purchases.subtitle": "Simamia maagizo ya manunuzi kutoka kwa wasambazaji, stoki iliyoingia, na akaunti za wasambazaji.",
    "purchases.totalPurchases": "Jumla ya Manunuzi",
    "purchases.monthlySpending": "Gharama za Mwezi",
    "purchases.pendingDeliveries": "Mizigo Inayosubiri",
    "purchases.activeSuppliers": "Wasambazaji Hai",
    "purchases.newPurchase": "Ununuzi Mpya",
    "purchases.tabOrders": "Historia ya Manunuzi / Stoki Iliyoingia",
    "purchases.tabSuppliers": "Wasambazaji",
    "purchases.orderId": "Namba ya Agizo",
    "purchases.supplier": "Msambazaji",
    "purchases.items": "Bidhaa na Idadi",
    "purchases.totalCost": "Gharama ya Jumla",
    "purchases.status": "Hali",
    "purchases.date": "Tarehe na Saa",
    "purchases.received": "Imepokelewa",
    "purchases.pending": "Inasubiri",
    "purchases.cancelled": "Imeghairiwa",

    // Production Aliases
    "production.inProgress": "Inaendelea",
    "production.completed": "Zimekamilika",
    "production.planned": "Iliyopangwa",
    "production.cancelled": "Imeghairiwa",
    "purchases.selectSupplier": "Chagua Msambazaji",
    "purchases.noSupplier": "Bila Msambazaji (Manunuzi ya Moja kwa Moja)",
    "purchases.selectProduct": "Chagua Bidhaa",
    "purchases.quantity": "Idadi",
    "purchases.buyingPrice": "Bei ya Kununua",
    "purchases.notes": "Maelezo / Namba ya Ankara",
    "purchases.addItem": "Ongeza Bidhaa Nyingine",
    "purchases.completePurchase": "Pokea Stoki na Hifadhi",
    "purchases.noPurchases": "Hakuna kumbukumbu za manunuzi bado.",

    // Production
    "production.title": "Uzalishaji",
    "production.subtitle": "Fuatilia awamu za utengenezaji, matumizi ya malighafi, na bidhaa zilizokamilika.",
    "production.activeRuns": "Awamu Zinazoendelea",
    "production.completedToday": "Zilizokamilika Leo",
    "production.totalOutput": "Jumla ya Bidhaa Zilizotengenezwa",
    "production.materialCost": "Gharama ya Malighafi",
    "production.newRun": "Awamu Mpya ya Uzalishaji",
    "production.batchNumber": "Namba ya Awamu",
    "production.outputProduct": "Bidhaa Inayotengenezwa",
    "production.rawMaterials": "Malighafi (Zinazotumika)",
    "production.quantityToProduce": "Lengo la Idadi",
    "production.quantityProduced": "Idadi Iliyotengenezwa",
    "production.statusPlanned": "Imepangwa",
    "production.statusInProgress": "Inaendelea",
    "production.statusCompleted": "Imekamilika",
    "production.statusCancelled": "Imeghairiwa",
    "production.startRun": "Anza Uzalishaji",
    "production.completeRun": "Kamilisha na Sasisha Stoki",
    "production.cancelRun": "Ghairi Awamu",
    "production.materialsPerUnit": "Kiasi cha malighafi kwa kila kipande",
    "production.totalRequired": "Jumla iliyotumika",
    "production.noRuns": "Hakuna awamu za uzalishaji zilizorekodiwa bado.",
    "production.notes": "Maelekezo / Maelezo ya Uzalishaji",

    // HR & Finance Tabs
    "hrm.tabStaff": "Wafanyakazi na Mahudhurio",
    "hrm.tabUserAccess": "Usimamizi wa Akaunti na Majukumu",
    "expenses.tabExpenses": "Matumizi",
    "expenses.tabBilling": "Bili na Vifurushi",

    // Dashboard
    "dashboard.title": "Dashibodi",
    "dashboard.subtitle": "Muhtasari wa utendaji wa duka lako leo.",
    "dashboard.todaySales": "Mauzo ya Leo",
    "dashboard.transactions": "Miamala",
    "dashboard.lowStock": "Stoki Chini",
    "dashboard.cashVsMpesa": "Taslimu dhidi ya malipo ya kidijitali",
    "dashboard.receiptsIssued": "Risiti zilizotolewa leo",
    "dashboard.checkInventory": "Angalia hesabu kabla ya kufunga",
    "dashboard.paymentSplit": "Mgawanyo wa malipo ya leo",
    "dashboard.salesTrend": "Mwenendo wa Mauzo",
    "dashboard.stockByCategory": "Stoki kwa Kategoria",
    "dashboard.totalItems": "Jumla ya Bidhaa",
    "dashboard.alerts": "Tahadhari na Shughuli za Hivi Karibuni",
    "dashboard.newSale": "Mauzo mapya",
    "dashboard.addProduct": "Ongeza Bidhaa",
    "dashboard.recordExpense": "Andika matumizi",
    "dashboard.daily": "Kila Siku",
    "dashboard.weekly": "Kila Wiki",
    "dashboard.monthly": "Kila Mwezi",
    "dashboard.calculator": "Calculator",

    // Sales
    "sales.customer": "Mteja",
    "sales.customerName": "Jina la Mteja",
    "sales.phone": "Simu",
    "sales.walkIn": "Mteja wa Kawaida",
    "sales.scanBarcode": "Skana (USB)",
    "sales.searchProducts": "Tafuta Bidhaa",
    "sales.searchOrScan": "Tafuta au skani kwa skana ya USB",
    "sales.cart": "Cart",
    "sales.barcodeOrSearch": "Skani barcode au tafuta ili kuongeza bidhaa",
    "sales.qty": "Idadi",
    "sales.product": "Bidhaa",
    "sales.price": "Bei",
    "sales.subtotal": "Jumla Ndogo",
    "sales.discount": "Punguzo",
    "sales.total": "Jumla",
    "sales.cash": "Taslimu",
    "sales.mpesa": "Mobile Money",
    "sales.mpesaCode": "Namba ya muamala",
    "sales.transactionCode": "Nambari ya muamala",
    "sales.completeSale": "Maliza mauzo",
    "sales.printReceipt": "Chapisha risiti",
    "sales.saveAsDraft": "Hifadhi kama rasimu",
    "sales.invoice": "Ankara",
    "sales.autoGenerated": "Nambari ya ankara iliyotengenezwa kiotomatiki",
    "sales.dateTime": "Tarehe na Saa",
    "sales.enterAmount": "Ingiza kiasi",
    "sales.enterPhone": "Ingiza nambari ya simu ya mteja",
    "sales.selectCustomer": "Chagua mteja",

    // Inventory
    "inventory.title": "Hesabu ya Stoo",
    "inventory.searchPlaceholder": "Tafuta bidhaa...",
    "inventory.import": "Leta",
    "inventory.export": "Pakua",
    "inventory.addProduct": "Ongeza Bidhaa",
    "inventory.category": "Kundi",
    "inventory.categories": "Makundi",
    "inventory.code": "Kodi / Barcode",
    "inventory.name": "Jina la Bidhaa",
    "inventory.stock": "Hesabu ya Stoki",
    "inventory.sellingPrice": "Bei ya Kuuza",
    "inventory.buyingPrice": "Bei ya Kununua",
    "inventory.priceCol": "Bei",
    "inventory.actions": "Vitendo",
    "inventory.low": "CHINI",
    "inventory.profit": "Faida",
    "inventory.profitPercent": "Faida %",
    "inventory.totalStockValue": "Thamani ya Stoki",
    "inventory.all": "Bidhaa Zote",
    "inventory.inStock": "Zilizopo Stoo",
    "inventory.lowStock": "Stoki Chini",
    "inventory.outOfStock": "Zimeisha",

    // Add Product
    "addProduct.title": "Ongeza Bidhaa Mpya",
    "addProduct.back": "Rudi kwenye Hesabu",
    "addProduct.generalInfo": "Taarifa za Jumla",
    "addProduct.productName": "Jina la Bidhaa",
    "addProduct.productNamePlaceholder": "mf. Brashi ya Rangi 4 inchi",
    "addProduct.productCode": "Kodi ya Bidhaa (SKU)",
    "addProduct.category": "Kategoria",
    "addProduct.selectCategory": "Chagua Kategoria",
    "addProduct.addCategoryNow": "Ongeza kategoria sasa",
    "addProduct.barcode": "Barcode",
    "addProduct.scanOrEnter": "Lenga hapa na scan na skana ya USB, au andika",
    "addProduct.unitType": "Aina ya Kipimo",
    "addProduct.pricingStock": "Bei na Stoki",
    "addProduct.buyingPrice": "Bei ya Kununua",
    "addProduct.sellingPrice": "Bei ya Kuuza",
    "addProduct.initialStock": "Idadi ya Stoki ya Awali",
    "addProduct.lowStockAlert": "Tahadhari ya Stoki Chini",
    "addProduct.lowStockHint": "Juulisha stoki inaposhuka chini ya hii",
    "addProduct.cancel": "Ghairi",
    "addProduct.save": "Hifadhi Bidhaa",
    "addProduct.productImage": "Picha ya Bidhaa",

    // Categories
    "category.building": "Vifaa vya Ujenzi",
    "category.tools": "Zana",
    "category.electrical": "Umeme",
    "category.plumbing": "Mabomba",
    "category.paint": "Rangi na Vimumunyisho",

    // Units
    "unit.piece": "Kipande (pc)",
    "unit.kg": "Kilogramu (kg)",
    "unit.meter": "Mita (m)",
    "unit.liter": "Lita (L)",
    "unit.box": "Sanduku",

    // Customers
    "customers.title": "Wateja",
    "customers.searchPlaceholder": "Tafuta jina au simu ya mteja...",
    "customers.addCustomer": "Ongeza Mteja",
    "customers.name": "Jina la Mteja",
    "customers.phoneNumber": "Nambari ya Simu",
    "customers.type": "Aina",
    "customers.creditBalance": "Salio la Mkopo (TSH)",
    "customers.contractor": "Mkandarasi",
    "customers.retail": "Rejareja",
    "customers.pay": "Lipa",
    "customers.history": "Historia",

    // Suppliers
    "suppliers.title": "Wasambazaji",
    "suppliers.totalSuppliers": "Wasambazaji Wote",
    "suppliers.pendingPayments": "Malipo Yanayosubiri",
    "suppliers.lastPurchase": "Ununuzi wa Mwisho",
    "suppliers.daysAgo": "Siku Zilizopita",
    "suppliers.searchPlaceholder": "Tafuta jina au mawasiliano ya msambazaji...",
    "suppliers.addSupplier": "Ongeza Msambazaji",
    "suppliers.supplierName": "Jina la Msambazaji",
    "suppliers.contact": "Mawasiliano",
    "suppliers.pendingPayment": "Malipo Yanayosubiri (TSH)",
    "suppliers.paid": "Imelipwa",

    // Expenses
    "expenses.title": "Matumizi",
    "expenses.totalExpenses": "JUMLA YA MATUMIZI (OCT)",
    "expenses.operationalCosts": "GHARAMA ZA UENDESHAJI",
    "expenses.stockPurchases": "UNUNUZI WA STOKI",
    "expenses.utilitiesRent": "Huduma na Kodi",
    "expenses.pendingInvoices": "Ankara zinazosubiri",
    "expenses.recentExpenses": "Matumizi ya Hivi Karibuni",
    "expenses.searchPlaceholder": "Tafuta matumizi...",
    "expenses.date": "Tarehe",
    "expenses.description": "Maelezo",
    "expenses.category": "Kategoria",
    "expenses.amount": "Kiasi",
    "expenses.payMethod": "Njia ya Malipo",
    "expenses.addNewExpense": "Ongeza Matumizi Mapya",
    "expenses.expenseTitle": "Jina la Matumizi",
    "expenses.expensePlaceholder": "mf. Bill ya Umeme",
    "expenses.amountTsh": "Kiasi",
    "expenses.paymentMethod": "Njia ya Malipo",
    "expenses.saveExpense": "Hifadhi Matumizi",
    "expenses.categoryBreakdown": "Mgawanyo wa Kategoria",

    // Expense categories
    "expenseCategory.utilities": "Huduma",
    "expenseCategory.rent": "Kodi",
    "expenseCategory.transport": "Usafiri",
    "expenseCategory.food": "Chakula",
    "expenseCategory.office": "Ofisi",
    "expenseCategory.stock": "Ununuzi wa Stoki",

    // Reports
    "reports.title": "Ripoti",
    "reports.salesSummary": "Muhtasari wa Mauzo",
    "reports.stockReport": "Ripoti ya Stoki",
    "reports.profitLoss": "Faida na Hasara",
    "reports.customerLedger": "Leja ya Mteja",
    "reports.exportPdf": "Toa PDF",
    "reports.exportExcel": "Toa Excel",
    "reports.salesPeriod": "Muhtasari wa Mauzo (Kipindi Kilichochaguliwa)",
    "reports.bestSelling": "Bidhaa Zinazouzwa Zaidi",
    "reports.salesByCategory": "Mauzo kwa Kategoria",
    "reports.recentTransactions": "Miamala ya Hivi Karibuni",
    "reports.customer": "Mteja",
    "reports.payment": "Malipo",
    "reports.status": "Hali",
    "reports.completed": "Imekamilika",
    "reports.salesTrend": "Mwenendo wa Mauzo",
    "reports.topCustomers": "Wateja Wakuu",
    "reports.expenseBreakdown": "Mgawanyo wa Matumizi",
    "reports.lowStockProducts": "Bidhaa zenye Stoki Kidogo",
    "reports.amount": "Kiasi",
    "reports.amountTsh": "Kiasi",
    "reports.noSalesData": "Hakuna data ya mauzo bado",
    "reports.noSalesYet": "Hakuna mauzo bado",
    "reports.noData": "Hakuna data",
    "reports.daily": "Kila Siku",
    "reports.weekly": "Kila Wiki",
    "reports.monthly": "Kila Mwezi",
    "reports.custom": "Kipindi Maalum",
    "reports.from": "Kuanzia",
    "reports.to": "Hadi",
    "reports.inventoryValuation": "Thamani ya Stoki",
    "reports.totalValue": "Thamani ya Jumla",
    "reports.totalProducts": "Idadi ya Bidhaa",
    "reports.lowStock": "Stoki Kidogo",
    "reports.outOfStock": "Hakuna Stoki",
    "reports.valueByProduct": "Thamani kwa Bidhaa",
    "reports.product": "Bidhaa",
    "reports.cost": "Bei ya Ununuzi",
    "reports.value": "Thamani",
    "reports.profitAndLoss": "Faida na Hasara",
    "reports.salesRevenue": "Mapato ya Mauzo",
    "reports.expenses": "Matumizi",
    "reports.netProfit": "Faida Halisi",
    "reports.profitMargin": "Kiwango cha Faida",
    "reports.salesTab": "Mauzo",
    "reports.inventoryTab": "Stoki",

    // Settings
    "settings.title": "Mipangilio",
    "settings.subtitle": "Simamia mipangilio ya duka lako, watumiaji, na upendeleo.",
    "settings.shopDetails": "Maelezo ya Duka",
    "settings.shopName": "Jina la Duka",
    "settings.phoneNumber": "Nambari ya Simu",
    "settings.location": "Mahali",
    "settings.saveChanges": "Hifadhi Mabadiliko",
    "settings.languagePrefs": "Lugha na Upendeleo",
    "settings.language": "Lugha",
    "settings.english": "Kiingereza",
    "settings.swahili": "Kiswahili",
    "settings.lowStockAlerts": "Tahadhari za Stoki Chini",
    "settings.notifyLow": "Arifu bidhaa stoo ikipungua",
    "settings.autoPrint": "Chapisha Risiti Kiotomatiki",
    "settings.printAfterSale": "Chapisha baada ya kila uuzaji",
    "settings.backupRestore": "Hifadhi na Rejesha",
    "settings.backupDesc": "Tengeneza nakala ya data yako au rejesha kutoka nakala ya awali.",
    "settings.createBackup": "Tengeneza Nakala",
    "settings.restoreBackup": "Rejesha Nakala",
    "settings.lastBackup": "Nakala ya mwisho",
    "settings.userManagement": "Usimamizi wa Watumiaji",
    "settings.addUser": "Ongeza Mtumiaji",
    "settings.role": "Jukumu",
    "settings.active": "Hai",
    "settings.inactive": "Haipo Hai",
    "settings.receiptCustomization": "Ubinafsishaji wa Risiti",
    "settings.receiptHeader": "Kichwa cha Risiti",
    "settings.receiptFooter": "Mwisho wa risiti",
    "settings.logo": "Nembo",
    "settings.taxRate": "Kiwango cha Kodi (%)",
    "settings.saveReceiptSettings": "Hifadhi Mipangilio ya Risiti",

    // Receipt
    "receipt.title": "RISITI YA MAUZO",
    "receipt.invoice": "Ankara",
    "receipt.date": "Tarehe",
    "receipt.customer": "Mteja",
    "receipt.cashier": "Muuzaji",
    "receipt.qty": "Idadi",
    "receipt.item": "Bidhaa",
    "receipt.price": "Bei",
    "receipt.total": "Jumla",
    "receipt.subtotal": "Jumla Ndogo",
    "receipt.discount": "Punguzo",
    "receipt.grandTotal": "JUMLA KUU",
    "receipt.paymentMethod": "Malipo",
    "receipt.mpesaCode": "Namba ya muamala",
    "receipt.thankYou": "Asante kwa kununua kwetu!",
    "receipt.comeAgain": "Karibu tena!",

    // Inventory Category Bulk
    "inventory.changeCategory": "Badilisha Kategoria",
    "inventory.deleteSelected": "Futa Zilizochaguliwa",
    "inventory.exportSelected": "Pakua Zilizochaguliwa",
    "inventory.newCategory": "Kategoria mpya",
    "inventory.selectCategory": "Chagua kategoria",
    "inventory.applyCategory": "Tumia Kategoria",
    "inventory.productsWillBeUpdated": "bidhaa zitabadilishwa.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "sw";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const swahiliTermsMap: Record<string, string> = {
    all: "Zote",
    cancel: "Ghairi",
    save: "Hifadhi",
    delete: "Futa",
    edit: "Hariri",
    search: "Tafuta",
    category: "Kundi",
    categories: "Makundi",
    code: "Kodi",
    name: "Jina",
    stock: "Stoki",
    price: "Bei",
    sellingprice: "Bei ya Kuuza",
    buyingprice: "Bei ya Kununua",
    inprogress: "Inaendelea",
    completed: "Zimekamilika",
    planned: "Iliyopangwa",
    cancelled: "Imeghairiwa",
    received: "Imepokelewa",
    pending: "Inasubiri",
    status: "Hali",
    actions: "Vitendo",
    total: "Jumla",
    add: "Ongeza",
    addproduct: "Ongeza Bidhaa",
    addcustomer: "Ongeza Mteja",
    addexpense: "Ongeza Matumizi",
    newpurchase: "Ununuzi Mpya",
    newrun: "Uzalishaji Mpya",
    date: "Tarehe",
    phone: "Simu",
    notes: "Maelezo",
    quantity: "Idadi",
    customer: "Mteja",
    supplier: "Msambazaji",
  };

  const formatKeyFallback = (k: string, lang: Language): string => {
    const lastPart = k.includes(".") ? k.split(".").pop() || k : k;
    const cleanLower = lastPart.toLowerCase().replace(/[_\s-]/g, "");

    if (lang === "sw" && swahiliTermsMap[cleanLower]) {
      return swahiliTermsMap[cleanLower];
    }

    return lastPart
      .replace(/([A-Z])/g, " $1")
      .replace(/[_-]/g, " ")
      .replace(/^\w/, (c) => c.toUpperCase())
      .trim();
  };

  const t = (key: string): string => {
    if (!key) return "";
    const curLang = translations[language] || {};
    if (curLang[key]) return curLang[key];

    const fallbackLang = language === "sw" ? translations["en"] : translations["sw"];
    if (fallbackLang && fallbackLang[key]) return fallbackLang[key];

    return formatKeyFallback(key, language);
  };

  useEffect(() => {
    const saved = localStorage.getItem("app-language");
    if (saved && (saved === "en" || saved === "sw")) {
      setLanguageState(saved);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
